# Generated by Django 4.1.5 on 2023-05-05 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('emblem', models.ImageField(upload_to='emblems/%y/%m/%d')),
                ('shape', models.TextField()),
                ('area', models.FloatField(help_text='Squared Area in Km')),
                ('theme', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('red', 'Red'), ('brown', 'Brown')], max_length=10)),
                ('population', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovernorateLanguageBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('governor', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('govObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governorates', to='governorates.governorate', verbose_name='governorate')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.language', verbose_name='language')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('govObject', 'lang')},
            },
        ),
    ]
