# Generated by Django 4.1.5 on 2023-07-01 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_remove_ticketlanguagebased_category_and_more'),
        ('categories', '0002_ticketclasscategory_ticketclasscategorylanguagebased'),
        ('landmark_events', '0008_rename_is_main_landmarkevent_ismain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('package_maximium_budget', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('days', models.IntegerField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TourPackageTourismCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('tourism_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.tourismcategory')),
                ('tourpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_packages.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='TourPackageTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
                ('tourpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_packages.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='TourPackageLandmarkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmark_events.landmarkevent')),
                ('tourpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_packages.tourpackage')),
            ],
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='events',
            field=models.ManyToManyField(related_name='events', through='tour_packages.TourPackageLandmarkEvent', to='landmark_events.landmarkevent'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tickets',
            field=models.ManyToManyField(related_name='tickets', through='tour_packages.TourPackageTicket', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tourism_categories',
            field=models.ManyToManyField(related_name='tourism_categories', through='tour_packages.TourPackageTourismCategory', to='categories.tourismcategory'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='user_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
