# Generated by Django 4.1.5 on 2023-06-14 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landmark_events', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('package_maximium_budget', models.FloatField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('events', models.ManyToManyField(related_name='events', to='landmark_events.landmarkevent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TourPackageTourismCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('tourism_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.tourismcategory')),
                ('tourpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_packages.tourpackage')),
            ],
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tourism_categories',
            field=models.ManyToManyField(related_name='tourism_categories', through='tour_packages.TourPackageTourismCategory', to='categories.tourismcategory'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='user_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
