# Generated by Django 4.1.5 on 2023-05-05 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('isMain', models.BooleanField(default=False, verbose_name='Main')),
                ('active', models.BooleanField(default=True)),
                ('landmarkObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmarks.landmark', verbose_name='landmark')),
            ],
        ),
        migrations.CreateModel(
            name='LandmarkEventLanguageBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('eventObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmark_events.landmarkevent', verbose_name='Event')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.language', verbose_name='language')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('eventObject', 'lang')},
            },
        ),
    ]
