# Generated by Django 4.1.5 on 2023-06-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landmarks', '0001_initial'),
        ('landmark_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmarkevent',
            name='landmarkObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmarks.landmark', verbose_name='landmark'),
        ),
        migrations.AlterUniqueTogether(
            name='landmarkeventlanguagebased',
            unique_together={('eventObject', 'lang')},
        ),
        migrations.AlterUniqueTogether(
            name='landmarkevent',
            unique_together={('name', 'landmarkObject')},
        ),
    ]
