# Generated by Django 4.1.5 on 2023-05-12 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landmark_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmarkevent',
            name='closeTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='landmarkevent',
            name='openTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
