# Generated by Django 4.1.5 on 2023-06-24 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landmark_events', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmarkevent',
            old_name='isMain',
            new_name='is_main',
        ),
        migrations.AddField(
            model_name='landmarkevent',
            name='end_Date',
            field=models.DateField(default='9999-12-31'),
        ),
        migrations.AddField(
            model_name='landmarkevent',
            name='is_eternel',
            field=models.BooleanField(default=True, verbose_name='Eternel'),
        ),
        migrations.AddField(
            model_name='landmarkevent',
            name='start_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='landmarkevent',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='landmarkeventlanguagebased',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
