# Generated by Django 4.1.5 on 2023-06-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0012_alter_landmark_tourismcategoryobject'),
        ('landmark_events', '0003_alter_landmarkevent_closetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landmarkevent',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='landmarkevent',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='landmarkevent',
            unique_together={('name', 'landmarkObject')},
        ),
    ]
