# Generated by Django 4.1.5 on 2023-06-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark_events', '0003_rename_ismain_landmarkevent_is_main_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmarkevent',
            old_name='end_Date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='landmarkevent',
            old_name='start_Date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='landmarkevent',
            name='is_eternel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='landmarkevent',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
