# Generated by Django 4.1.5 on 2023-06-24 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landmark_events', '0004_rename_end_date_landmarkevent_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarkevent',
            name='end_date',
            field=models.DateTimeField(default='9999-12-31 23:59:59'),
        ),
        migrations.AlterField(
            model_name='landmarkevent',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
