# Generated by Django 4.1.5 on 2023-06-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark_events', '0006_alter_landmarkevent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarkevent',
            name='end_date',
            field=models.DateTimeField(default='9999-12-30 23:59:59.314354+00:00'),
        ),
    ]
