# Generated by Django 4.1.5 on 2023-06-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark_events', '0007_alter_landmarkevent_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmarkevent',
            old_name='is_main',
            new_name='isMain',
        ),
    ]
