# Generated by Django 4.1.5 on 2023-05-05 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import landmarks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('tourism_categories', '0001_initial'),
        ('governorates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, unique=True)),
                ('image', models.ImageField(upload_to=landmarks.models.LandmarkImagesPath)),
                ('area', models.FloatField(help_text='Squared Area in metre')),
                ('location', models.CharField(help_text='google maps link ', max_length=200)),
                ('height', models.FloatField(default=1, help_text='height in metre')),
                ('foundationDate', models.DateField(default=django.utils.timezone.now, verbose_name='Foundation Date')),
                ('foundationDateEra', models.CharField(choices=[('BC', 'BC'), ('AD', 'AD')], default='AD', max_length=3, verbose_name='Foundation Date Era')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('govObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governorates.governorate')),
                ('tourismCategoryObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism_categories.tourismcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TourismTypesLandmarkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism_categories.tourismcategory', verbose_name='core')),
                ('landmarkObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmarks.landmark', verbose_name='landmark')),
            ],
        ),
        migrations.CreateModel(
            name='LandmarkLanguageBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('founder', models.CharField(blank=True, max_length=70, null=True)),
                ('description', models.TextField()),
                ('address', models.TextField(max_length=300)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('landmarkObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmarks.landmark', verbose_name='landmark')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.language', verbose_name='language')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('landmarkObject', 'lang')},
            },
        ),
    ]
