# Generated by Django 4.1.5 on 2023-06-14 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import landmarks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('governorates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_alter_review_user'),
        ('system', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('image', models.ImageField(default='defaults/landmark_default.jpg', upload_to=landmarks.models.LandmarkImagesPath)),
                ('area', models.FloatField(help_text='Squared Area in metre')),
                ('location_link', models.URLField(help_text='google maps link ')),
                ('height', models.FloatField(default=1, help_text='height in metre')),
                ('foundationDate', models.DateField(default=django.utils.timezone.now, verbose_name='Foundation Date')),
                ('foundationDateEra', models.CharField(choices=[('BC', 'BC'), ('AD', 'AD')], default='AD', max_length=3, verbose_name='Foundation Date Era')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('govObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governorates.governorate')),
            ],
        ),
        migrations.CreateModel(
            name='TourismTypesLandmarkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.tourismcategory', verbose_name='core')),
                ('landmarkObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmarks.landmark', verbose_name='landmark')),
            ],
        ),
        migrations.CreateModel(
            name='LandmarkReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmarks.landmark')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
            options={
                'verbose_name': 'Landmark Review',
                'verbose_name_plural': 'Landmark Reviews',
                'ordering': ['-created'],
                'unique_together': {('landmark', 'review')},
            },
        ),
        migrations.CreateModel(
            name='LandmarkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.image')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmarks.landmark')),
            ],
            options={
                'verbose_name': 'Landmark Image',
                'verbose_name_plural': 'Landmark Images',
                'ordering': ['-created'],
                'unique_together': {('landmark', 'image')},
            },
        ),
        migrations.AddField(
            model_name='landmark',
            name='images',
            field=models.ManyToManyField(blank=True, through='landmarks.LandmarkImage', to='system.image'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='reviews',
            field=models.ManyToManyField(blank=True, through='landmarks.LandmarkReview', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='tourismCategoryObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.tourismcategory'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='typeCategoryObject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.typecategory'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='user_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LandmarkLanguageBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('founder', models.CharField(blank=True, max_length=70, null=True)),
                ('description', models.TextField()),
                ('address', models.TextField(max_length=300)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('category_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.typecategorylanguagebased', verbose_name='category type')),
                ('landmarkObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmarks.landmark', verbose_name='landmark')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.language', verbose_name='language')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('landmarkObject', 'lang')},
            },
        ),
    ]
