# Generated by Django 4.1.5 on 2023-06-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='location_link',
            field=models.URLField(help_text='google maps link ', max_length=500),
        ),
    ]
