# Generated by Django 4.1.5 on 2023-05-12 16:54

from django.db import migrations, models
import landmarks.models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='image',
            field=models.ImageField(default='defaults/landmark_default.jpg', upload_to=landmarks.models.LandmarkImagesPath),
        ),
    ]
