# Generated by Django 4.1.5 on 2023-05-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0003_alter_landmarklanguagebased_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='location',
            field=models.TextField(help_text='google maps link '),
        ),
        migrations.AlterField(
            model_name='landmarklanguagebased',
            name='description',
            field=models.TextField(),
        ),
    ]
