# Generated by Django 4.1.5 on 2023-06-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0003_delete_tourismtypeslandmarklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarklanguagebased',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='landmarklanguagebased',
            name='founder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landmarklanguagebased',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
