# Generated by Django 4.1.5 on 2023-06-24 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_coordinate'),
        ('landmarks', '0004_alter_landmarklanguagebased_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='coordinates',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='system.coordinate'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='height',
            field=models.FloatField(blank=True, help_text='height in metre'),
        ),
    ]
