# Generated by Django 4.1.5 on 2023-05-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0004_alter_landmark_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
