# Generated by Django 4.1.5 on 2023-05-25 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0005_alter_landmark_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Landmark Image',
                'verbose_name_plural': 'Landmark Images',
                'ordering': ['-created'],
            },
        ),
    ]
