# Generated by Django 4.1.5 on 2023-06-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_ticketclasscategory_ticketclasscategorylanguagebased'),
        ('landmarks', '0006_landmarktourismcategory_landmark_tourism_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landmarktourismcategory',
            options={'ordering': ['id'], 'verbose_name': 'Landmark Tourism Category', 'verbose_name_plural': 'Landmark Tourism Categories'},
        ),
        migrations.AddField(
            model_name='landmarklanguagebased',
            name='category_tourism_list',
            field=models.ManyToManyField(to='categories.tourismcategorylanguagebased', verbose_name='tourism categories'),
        ),
    ]
