# Generated by Django 4.1.5 on 2023-05-25 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0006_landmarkimage'),
        ('system', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmarkimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.image'),
        ),
        migrations.AddField(
            model_name='landmarkimage',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmarks.landmark'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='images',
            field=models.ManyToManyField(blank=True, through='landmarks.LandmarkImage', to='system.image'),
        ),
        migrations.AlterUniqueTogether(
            name='landmarkimage',
            unique_together={('landmark', 'image')},
        ),
    ]
