# Generated by Django 4.1.5 on 2023-05-27 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_images_alter_reviewimage_image_and_more'),
        ('landmarks', '0007_landmarkimage_image_landmarkimage_landmark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarkReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmarks.landmark')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
            options={
                'verbose_name': 'Landmark Review',
                'verbose_name_plural': 'Landmark Reviews',
                'ordering': ['-created'],
                'unique_together': {('landmark', 'review')},
            },
        ),
        migrations.AddField(
            model_name='landmark',
            name='reviews',
            field=models.ManyToManyField(blank=True, through='landmarks.LandmarkReview', to='reviews.review'),
        ),
    ]
