# Generated by Django 4.1.5 on 2023-06-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_ticketclasscategory_ticketclasscategorylanguagebased'),
        ('landmarks', '0007_alter_landmarktourismcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarklanguagebased',
            name='category_tourism_list',
            field=models.ManyToManyField(null=True, to='categories.tourismcategorylanguagebased', verbose_name='tourism categories'),
        ),
    ]
