# Generated by Django 4.1.5 on 2023-05-27 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landmarks', '0008_landmarkreview_landmark_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='user_created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
