# Generated by Django 4.1.5 on 2023-06-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_ticketclasscategory_ticketclasscategorylanguagebased'),
        ('landmarks', '0008_alter_landmarklanguagebased_category_tourism_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarklanguagebased',
            name='category_tourism_list',
            field=models.ManyToManyField(blank=True, to='categories.tourismcategorylanguagebased', verbose_name='tourism categories'),
        ),
    ]
