# Generated by Django 4.1.5 on 2023-06-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0009_alter_landmarklanguagebased_category_tourism_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmarklanguagebased',
            name='category_tourism_list',
        ),
    ]
