# Generated by Django 4.1.5 on 2023-07-04 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0010_remove_landmarklanguagebased_category_tourism_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='area',
            field=models.FloatField(help_text='Squared Area in metre', null=True),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='foundationDate',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Foundation Date'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='height',
            field=models.FloatField(default=None, help_text='height in metre', null=True),
        ),
    ]
