# Generated by Django 4.2.1 on 2023-06-11 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_categories', '0007_alter_typecategory_options'),
        ('landmarks', '0010_landmark_typecategoryobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmarklanguagebased',
            name='category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourism_categories.typecategorylanguagebased', verbose_name='category type'),
        ),
    ]
