# Generated by Django 4.1.5 on 2023-07-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0011_alter_landmark_area_alter_landmark_foundationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='num_of_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='location_link',
            field=models.URLField(help_text='embeded google maps link ', max_length=500),
        ),
    ]
