# Generated by Django 4.2.1 on 2023-06-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_categories', '0007_alter_typecategory_options'),
        ('landmarks', '0011_landmarklanguagebased_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='tourismCategoryObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourism_categories.tourismcategory'),
        ),
    ]
