# Generated by Django 4.1.5 on 2023-07-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0012_landmark_num_of_views_alter_landmark_location_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='area',
            field=models.FloatField(blank=True, help_text='Squared Area in metre', null=True),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='height',
            field=models.FloatField(blank=True, default=None, help_text='height in metre', null=True),
        ),
    ]
