# Generated by Django 4.1.5 on 2023-07-08 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0013_alter_landmark_area_alter_landmark_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='foundationDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Foundation Date'),
        ),
    ]
