# Generated by Django 4.1.5 on 2023-05-05 21:35

from django.db import migrations, models
import django.db.models.deletion
import tourism_categories.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('image', models.ImageField(upload_to=tourism_categories.models.TourismCategoryImagesPath)),
            ],
        ),
        migrations.CreateModel(
            name='TourismCategoryLanguageBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('categoryObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism_categories.tourismcategory', verbose_name='core')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.language', verbose_name='language')),
            ],
        ),
    ]
