# Generated by Django 4.1.5 on 2023-05-06 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tourismcategory',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date'),
        ),
        migrations.AddField(
            model_name='tourismcategorylanguagebased',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tourismcategorylanguagebased',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date'),
        ),
    ]
