# Generated by Django 4.1.5 on 2023-05-11 20:00

from django.db import migrations, models
import tourism_categories.models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_categories', '0002_tourismcategory_active_tourismcategory_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismcategory',
            name='image',
            field=models.ImageField(default='defaults/tourism_category_default.jpg', upload_to=tourism_categories.models.TourismCategoryImagesPath),
        ),
    ]
