# Generated by Django 4.1.5 on 2023-05-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_categories', '0003_alter_tourismcategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourismcategory',
            options={'verbose_name': 'TourismCategory'},
        ),
    ]
