# Generated by Django 4.1.5 on 2023-05-16 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_categories', '0004_alter_tourismcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourismcategory',
            options={'verbose_name': 'Tourism Category', 'verbose_name_plural': 'Tourism Categories'},
        ),
    ]
