# Generated by Django 4.2.1 on 2023-06-11 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_image'),
        ('tourism_categories', '0005_alter_tourismcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tourism Category',
                'verbose_name_plural': 'Tourism Categories',
            },
        ),
        migrations.CreateModel(
            name='TypeCategoryLanguageBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('categoryObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism_categories.typecategory', verbose_name='core')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.language', verbose_name='language')),
            ],
        ),
    ]
