# Generated by Django 4.2.1 on 2023-06-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_categories', '0006_typecategory_typecategorylanguagebased'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecategory',
            options={'verbose_name': 'Type Category', 'verbose_name_plural': 'Type Categories'},
        ),
    ]
