# Generated by Django 4.1.5 on 2023-06-14 17:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0002_image'),
        ('landmark_events', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('price', models.FloatField(help_text='Price in Egyptian Pounds')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('eventObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmark_events.landmarkevent', verbose_name='event')),
            ],
        ),
        migrations.CreateModel(
            name='TicketLanguageBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('foreigner', 'Foreigner'), ('foreigner student', 'foreigner Student'), ('egyptian', 'Egyptian'), ('arab', 'Arab'), ('student', 'Student'), ('أجنبي', 'أجنبى'), ('طالب أجنبي', 'طالب أجنبى'), ('مصري', 'مصرى'), ('عرب', 'عربى'), ('طالب', 'طالب')], max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.language', verbose_name='language')),
                ('ticketObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket', verbose_name='Ticket')),
            ],
        ),
    ]
