# Generated by Django 4.1.5 on 2023-05-05 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmark_events', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='eventObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landmark_events.landmarkevent', verbose_name='event'),
        ),
    ]
