# Generated by Django 4.1.5 on 2023-06-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_ticketclasscategory_ticketclasscategorylanguagebased'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlanguagebased',
            name='category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketClassObject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.ticketclasscategory', verbose_name='ticket_class'),
        ),
        migrations.AddField(
            model_name='ticketlanguagebased',
            name='ticket_class_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.ticketclasscategorylanguagebased', verbose_name='category type'),
        ),
    ]
