# Generated by Django 4.1.5 on 2023-05-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_eventobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlanguagebased',
            name='category',
            field=models.CharField(choices=[('foreigner', 'Foreigner'), ('foreigner student', 'foreigner Student'), ('egyptian', 'Egyptian'), ('arab', 'Arab'), ('student', 'Student'), ('أجنبي', 'أجنبى'), ('طالب أجنبي', 'طالب أجنبى'), ('مصري', 'مصرى'), ('عرب', 'عربى'), ('طالب', 'طالب')], max_length=20),
        ),
    ]
